#!bin/bash

# Start/stop the arp daemon.
#
### BEGIN INIT INFO
# Provides:          arp
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: arp table each minute
# Description:       
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/var/opt/arp.sh
PIDFILE=/var/run/arp.pid

. /lib/lsb/init-functions

case "$1" in

start)
 start-stop-daemon -Sbvmp $PIDFILE -x $DAEMON
 echo "$(date) arp table started" >> var/log/arp
;;
stop)
 start-stop-daemon -Kvp $PIDFILE
 echo "$(date) arp table stopped" >> var/log/arp
 ;;
restart)
 $0 stop
 $0 start
  ;;
 *)
 echo "please, use next commands: $0 {start|stop|restart|status}"
esac

exit 0
